services:
  tidal-ui:
    image: tidal-ui:latest
    container_name: tidal-ui
    ports:
      - '5000:5000'
    restart: unless-stopped
    volumes:
      - ${DATA_PATH}:/${DOWNLOAD_DIR}
    user: "1000:1000"
    environment:
      - NODE_ENV=production
      - TITLE=${TITLE}
      - REDIS_URL=${REDIS_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_TLS=${REDIS_TLS}
      - REDIS_CACHE_TTL_SECONDS=${REDIS_CACHE_TTL_SECONDS}
      - REDIS_CACHE_TTL_SEARCH_SECONDS=${REDIS_CACHE_TTL_SEARCH_SECONDS}
      - REDIS_CACHE_TTL_TRACK_SECONDS=${REDIS_CACHE_TTL_TRACK_SECONDS}
      - REDIS_CACHE_MAX_BODY_BYTES=${REDIS_CACHE_MAX_BODY_BYTES}
      - PORT=5000
      - DOWNLOAD_DIR=${DOWNLOAD_DIR}
