/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackIdRouteImport } from './routes/track/$id'
import { Route as PlaylistIdRouteImport } from './routes/playlist/$id'
import { Route as ArtistIdRouteImport } from './routes/artist/$id'
import { Route as AlbumIdRouteImport } from './routes/album/$id'
import { Route as ApiSpotifyPlaylistRouteRouteImport } from './routes/api/spotify-playlist/route'
import { Route as ApiSonglinkRouteRouteImport } from './routes/api/songlink/route'
import { Route as ApiProxyRouteRouteImport } from './routes/api/proxy/route'
import { Route as EmbedTrackIdRouteImport } from './routes/embed/track/$id'
import { Route as EmbedPlaylistIdRouteImport } from './routes/embed/playlist/$id'
import { Route as EmbedArtistIdRouteImport } from './routes/embed/artist/$id'
import { Route as EmbedAlbumIdRouteImport } from './routes/embed/album/$id'
import { Route as ApiArtworkTypeIdSizeRouteImport } from './routes/api/artwork/$type/$id/$size'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIdRoute = TrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistIdRoute = PlaylistIdRouteImport.update({
  id: '/playlist/$id',
  path: '/playlist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistIdRoute = ArtistIdRouteImport.update({
  id: '/artist/$id',
  path: '/artist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumIdRoute = AlbumIdRouteImport.update({
  id: '/album/$id',
  path: '/album/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpotifyPlaylistRouteRoute = ApiSpotifyPlaylistRouteRouteImport.update({
  id: '/api/spotify-playlist',
  path: '/api/spotify-playlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSonglinkRouteRoute = ApiSonglinkRouteRouteImport.update({
  id: '/api/songlink',
  path: '/api/songlink',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyRouteRoute = ApiProxyRouteRouteImport.update({
  id: '/api/proxy',
  path: '/api/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedTrackIdRoute = EmbedTrackIdRouteImport.update({
  id: '/embed/track/$id',
  path: '/embed/track/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedPlaylistIdRoute = EmbedPlaylistIdRouteImport.update({
  id: '/embed/playlist/$id',
  path: '/embed/playlist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedArtistIdRoute = EmbedArtistIdRouteImport.update({
  id: '/embed/artist/$id',
  path: '/embed/artist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedAlbumIdRoute = EmbedAlbumIdRouteImport.update({
  id: '/embed/album/$id',
  path: '/embed/album/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtworkTypeIdSizeRoute = ApiArtworkTypeIdSizeRouteImport.update({
  id: '/api/artwork/$type/$id/$size',
  path: '/api/artwork/$type/$id/$size',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/proxy': typeof ApiProxyRouteRoute
  '/api/songlink': typeof ApiSonglinkRouteRoute
  '/api/spotify-playlist': typeof ApiSpotifyPlaylistRouteRoute
  '/album/$id': typeof AlbumIdRoute
  '/artist/$id': typeof ArtistIdRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/track/$id': typeof TrackIdRoute
  '/embed/album/$id': typeof EmbedAlbumIdRoute
  '/embed/artist/$id': typeof EmbedArtistIdRoute
  '/embed/playlist/$id': typeof EmbedPlaylistIdRoute
  '/embed/track/$id': typeof EmbedTrackIdRoute
  '/api/artwork/$type/$id/$size': typeof ApiArtworkTypeIdSizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/proxy': typeof ApiProxyRouteRoute
  '/api/songlink': typeof ApiSonglinkRouteRoute
  '/api/spotify-playlist': typeof ApiSpotifyPlaylistRouteRoute
  '/album/$id': typeof AlbumIdRoute
  '/artist/$id': typeof ArtistIdRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/track/$id': typeof TrackIdRoute
  '/embed/album/$id': typeof EmbedAlbumIdRoute
  '/embed/artist/$id': typeof EmbedArtistIdRoute
  '/embed/playlist/$id': typeof EmbedPlaylistIdRoute
  '/embed/track/$id': typeof EmbedTrackIdRoute
  '/api/artwork/$type/$id/$size': typeof ApiArtworkTypeIdSizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/proxy': typeof ApiProxyRouteRoute
  '/api/songlink': typeof ApiSonglinkRouteRoute
  '/api/spotify-playlist': typeof ApiSpotifyPlaylistRouteRoute
  '/album/$id': typeof AlbumIdRoute
  '/artist/$id': typeof ArtistIdRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/track/$id': typeof TrackIdRoute
  '/embed/album/$id': typeof EmbedAlbumIdRoute
  '/embed/artist/$id': typeof EmbedArtistIdRoute
  '/embed/playlist/$id': typeof EmbedPlaylistIdRoute
  '/embed/track/$id': typeof EmbedTrackIdRoute
  '/api/artwork/$type/$id/$size': typeof ApiArtworkTypeIdSizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/proxy'
    | '/api/songlink'
    | '/api/spotify-playlist'
    | '/album/$id'
    | '/artist/$id'
    | '/playlist/$id'
    | '/track/$id'
    | '/embed/album/$id'
    | '/embed/artist/$id'
    | '/embed/playlist/$id'
    | '/embed/track/$id'
    | '/api/artwork/$type/$id/$size'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/proxy'
    | '/api/songlink'
    | '/api/spotify-playlist'
    | '/album/$id'
    | '/artist/$id'
    | '/playlist/$id'
    | '/track/$id'
    | '/embed/album/$id'
    | '/embed/artist/$id'
    | '/embed/playlist/$id'
    | '/embed/track/$id'
    | '/api/artwork/$type/$id/$size'
  id:
    | '__root__'
    | '/'
    | '/api/proxy'
    | '/api/songlink'
    | '/api/spotify-playlist'
    | '/album/$id'
    | '/artist/$id'
    | '/playlist/$id'
    | '/track/$id'
    | '/embed/album/$id'
    | '/embed/artist/$id'
    | '/embed/playlist/$id'
    | '/embed/track/$id'
    | '/api/artwork/$type/$id/$size'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiProxyRouteRoute: typeof ApiProxyRouteRoute
  ApiSonglinkRouteRoute: typeof ApiSonglinkRouteRoute
  ApiSpotifyPlaylistRouteRoute: typeof ApiSpotifyPlaylistRouteRoute
  AlbumIdRoute: typeof AlbumIdRoute
  ArtistIdRoute: typeof ArtistIdRoute
  PlaylistIdRoute: typeof PlaylistIdRoute
  TrackIdRoute: typeof TrackIdRoute
  EmbedAlbumIdRoute: typeof EmbedAlbumIdRoute
  EmbedArtistIdRoute: typeof EmbedArtistIdRoute
  EmbedPlaylistIdRoute: typeof EmbedPlaylistIdRoute
  EmbedTrackIdRoute: typeof EmbedTrackIdRoute
  ApiArtworkTypeIdSizeRoute: typeof ApiArtworkTypeIdSizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$id': {
      id: '/track/$id'
      path: '/track/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof TrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$id': {
      id: '/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof PlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$id': {
      id: '/artist/$id'
      path: '/artist/$id'
      fullPath: '/artist/$id'
      preLoaderRoute: typeof ArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$id': {
      id: '/album/$id'
      path: '/album/$id'
      fullPath: '/album/$id'
      preLoaderRoute: typeof AlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/spotify-playlist': {
      id: '/api/spotify-playlist'
      path: '/api/spotify-playlist'
      fullPath: '/api/spotify-playlist'
      preLoaderRoute: typeof ApiSpotifyPlaylistRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/songlink': {
      id: '/api/songlink'
      path: '/api/songlink'
      fullPath: '/api/songlink'
      preLoaderRoute: typeof ApiSonglinkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy': {
      id: '/api/proxy'
      path: '/api/proxy'
      fullPath: '/api/proxy'
      preLoaderRoute: typeof ApiProxyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/track/$id': {
      id: '/embed/track/$id'
      path: '/embed/track/$id'
      fullPath: '/embed/track/$id'
      preLoaderRoute: typeof EmbedTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/playlist/$id': {
      id: '/embed/playlist/$id'
      path: '/embed/playlist/$id'
      fullPath: '/embed/playlist/$id'
      preLoaderRoute: typeof EmbedPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/artist/$id': {
      id: '/embed/artist/$id'
      path: '/embed/artist/$id'
      fullPath: '/embed/artist/$id'
      preLoaderRoute: typeof EmbedArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/album/$id': {
      id: '/embed/album/$id'
      path: '/embed/album/$id'
      fullPath: '/embed/album/$id'
      preLoaderRoute: typeof EmbedAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artwork/$type/$id/$size': {
      id: '/api/artwork/$type/$id/$size'
      path: '/api/artwork/$type/$id/$size'
      fullPath: '/api/artwork/$type/$id/$size'
      preLoaderRoute: typeof ApiArtworkTypeIdSizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiProxyRouteRoute: ApiProxyRouteRoute,
  ApiSonglinkRouteRoute: ApiSonglinkRouteRoute,
  ApiSpotifyPlaylistRouteRoute: ApiSpotifyPlaylistRouteRoute,
  AlbumIdRoute: AlbumIdRoute,
  ArtistIdRoute: ArtistIdRoute,
  PlaylistIdRoute: PlaylistIdRoute,
  TrackIdRoute: TrackIdRoute,
  EmbedAlbumIdRoute: EmbedAlbumIdRoute,
  EmbedArtistIdRoute: EmbedArtistIdRoute,
  EmbedPlaylistIdRoute: EmbedPlaylistIdRoute,
  EmbedTrackIdRoute: EmbedTrackIdRoute,
  ApiArtworkTypeIdSizeRoute: ApiArtworkTypeIdSizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
